language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install setuptools==38.7   # Later versions require numdifftools to use PyScaffold==2.5.10
  - pip install -r requirements.txt
  - python setup.py install

script:
  - pytest -v -n 2 --durations=0 -k-slow
