language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install --upgrade setuptools pip   # To get enviroment markers to work
  - pip install -r requirements.txt
  - python setup.py install

script:
  - pytest -v -n 2 --durations=0
