language: python
python:
  - "2.7"
  - "3.6"
env:
  - TEST="pytest -v -n 2 --durations=10 -m 'not slow'"
  - TEST="python setup.py test --addopts "-v -n 2 -m 'not slow'""

install:
  - pip install -U -r requirements.txt --upgrade-strategy=eager
  - pip install -U -r requirements_test.txt --upgrade-strategy=eager
  - python setup.py install  

script: eval $TEST
