language: python
python:
  - "2.7"
  - "3.6"
env:
  - TEST="pytest"
  - TEST="setup.py test"


install:
  - |
    if [ "${TEST}" == "pytest" ]; then
      pip install -U -r requirements.txt --upgrade-strategy=eager
      pip install -U -r requirements_test.txt --upgrade-strategy=eager
      python setup.py install
    fi
  - |
    if [ "${TEST}" == "setup.py test" ]; then
      pip uninstall -y pytest
    fi

script:
  - |
    if [ "${TEST}" == "pytest" ]; then
      pytest -v -n 2 --durations=10 -m 'not slow'
    fi
  - |
    if [ "${TEST}" == "setup.py test" ]; then
      python setup.py test --addopts "-v -n 2 -m 'not slow'"
    fi

