version: 2.1

jobs:
  # Full tests
  test_python27_pytest:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: sudo pip install -U -r requirements.txt --upgrade-strategy=eager
      - run: sudo pip install -U -r requirements_test.txt --upgrade-strategy=eager
      - run: sudo python setup.py install
      - run: pytest -v -n 2 --durations=10 -m 'not slow'
  test_python35_pytest:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: sudo pip install -U -r requirements.txt --upgrade-strategy=eager
      - run: sudo pip install -U -r requirements_test.txt --upgrade-strategy=eager
      - run: sudo python setup.py install
      - run: pytest -v -n 2 --durations=10 -m 'not slow'
  test_python36_pytest:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install -U -r requirements.txt --upgrade-strategy=eager
      - run: sudo pip install -U -r requirements_test.txt --upgrade-strategy=eager
      - run: sudo python setup.py install
      - run: pytest -v -n 2 --durations=10 -m 'not slow'
  test_python37_pytest:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install -U -r requirements.txt --upgrade-strategy=eager
      - run: sudo pip install -U -r requirements_test.txt --upgrade-strategy=eager
      - run: sudo python setup.py install
      - run: pytest -v -n 2 --durations=10 -m 'not slow'

  # Quickly test that 'setup.py test' works
  test_python27_setup_test:
    docker:
      - image: circleci/python:2.7
    steps:
      - run: checkout
      - run: sudo python setup.py test --addopts "-v -k quad_df"
  test_python35_setup_test:
    docker:
      - image: circleci/python:3.5
    steps:
      - run: checkout
      - run: sudo python setup.py test --addopts "-v -k quad_df"
  test_python36_setup_test:
    docker:
      image: circleci/python:3.6
    steps:
      - run: checkout
      - run: sudo python setup.py test --addopts "-v -k quad_df"
  test_python37_setup_test:
    docker:
      - image: circleci/python:3.7
    steps:
      - run: checkout
      - run: sudo python setup.py test --addopts "-v -k quad_df"


workflows:
  test:
    jobs:
      - test_python27_pytest
      - test_python27_setup_test:
          requires:
            - test_python27_pytest

      - test_python35_pytest
      - test_python35_setup_test:
          requires:
            - test_python35_pytest

      - test_python36_pytest
      - test_python36_setup_test:
          requires:
            - test_python36_pytest

      - test_python37_pytest
      - test_python37_setup_test:
          requires:
            - test_python37_pytest


